repos:
-   repo: https://github.com/rkm/mirrors-dotnet-format
    rev: 2dab66c
    hooks:
    -   id: dotnet-format
        args: [--fix-style, warn]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
